/* Do not edit this file */
import { defineConfig } from 'vite'

export default defineConfig({
  publicDir: 'fake_dir_so_nothing_gets_copied',
  resolve: {
    alias: {
      // eslint-disable-next-line no-undef
      '@': require('path').resolve(__dirname, 'src'),
    },
  },
})
