/* Do not edit this file */
// eslint-disable-next-line no-undef
const path = require('path')
import { defineConfig } from 'vite'

export default defineConfig({
  build: {
    minify: false,
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@import "@/styles/globals/_all.scss";`
      }
    }
  },
  resolve: {
    alias: {
      // eslint-disable-next-line no-undef
      '@': path.resolve(__dirname, 'src'),
    },
  },
})
